apiVersion: v1
kind: Template
metadata:
  name: learning-resources
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: learning-resources
    spec:
      envName: ${ENV_NAME}
      title: learning-resources
      routePrefix: settings
      deploymentRepo: https://github.com/RedHatInsights/learning-resources
      API:
        versions:
          - v1
      frontend:
        paths:
          - /settings/learning-resources
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - title: Remote Host Configuration
          expandable: true
          routes:
            - appId: learning-resources
              title: Manage configuration
              href: /settings/learning-resources
            - appId: learning-resources
              title: Activation Keys
              href: /settings/learning-resources/activation-keys
      module:
        manifestLocation: /apps/learning-resources/fed-mods.json
        modules:
          - id: learning-resources
            module: ./RootApp
            routes:
              - pathname: /settings/learning-resources
        moduleID: learning-resources
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/learning-resources